[features]
seeds = false
skip-lint = false

[programs.localnet]
hybrid_defi = "B5KWHdNtiXtc1gS8aLobWS8hP3Xvdgi618VL81y8cw6V"
[programs.devnet]
hybrid_defi = "B5KWHdNtiXtc1gS8aLobWS8hP3Xvdgi618VL81y8cw6V"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "http://localhost:8899"
wallet = "/Users/joeymeere/.config/solana/id.json"

[[test.validator.clone]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"

[[test.validator.clone]]
address = "auth9SigNpDKz4sJJ1DfCTuZrZNSAgh9sFD3rboVmgg"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
